package sh.ravix.platform;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jboss.logging.Logger;
import sh.ravix.entity.Alias;
import sh.ravix.entity.AntispamSetting;
import sh.ravix.entity.AppSetting;
import sh.ravix.entity.CommandCheck;
import sh.ravix.entity.Domain;
import sh.ravix.entity.InstallLog;
import sh.ravix.entity.Mailbox;
import sh.ravix.entity.PackageStatus;

/**
 * Renders the panel's database state into real mail-stack configuration
 * (Postfix virtual maps, Dovecot passwd-file, OpenDKIM key/sign tables, Rspamd
 * thresholds) and reloads the affected services. On Linux it runs
 * postmap/systemctl; elsewhere it still writes the files so the output is
 * verifiable, but skips the reloads.
 */
@ApplicationScoped
public class ProvisioningService {

    private static final Logger LOG = Logger.getLogger(ProvisioningService.class);

    @Inject
    PlatformService platform;

    @Inject
    CloudflareService cloudflare;

    @Inject
    RadicaleService radicale;

    @ConfigProperty(name = "ravix.provision.postfix-dir") String postfixDir;
    @ConfigProperty(name = "ravix.provision.dovecot-userfile") String dovecotUserfile;
    @ConfigProperty(name = "ravix.provision.dkim-dir") String dkimDir;
    @ConfigProperty(name = "ravix.provision.rspamd-dir") String rspamdDir;
    @ConfigProperty(name = "ravix.provision.vmail-base") String vmailBase;
    @ConfigProperty(name = "ravix.provision.vmail-uid") String vmailUid;
    @ConfigProperty(name = "ravix.provision.vmail-gid") String vmailGid;

    @ConfigProperty(name = "ravix.panel-port", defaultValue = "9162") int panelPort;
    @ConfigProperty(name = "quarkus.http.port", defaultValue = "8080") int backendPort;

    private static final String WEB_DIR = "/var/www/ravix";
    private static final String SSL_DIR = "/etc/ravix/ssl";

    public record Result(List<String> files, boolean reloaded) {}

    /** Re-render everything that depends on domains/mailboxes/aliases. */
    public Result syncMailData() {
        List<String> files = new ArrayList<>();
        files.addAll(renderPostfix());
        files.add(renderDovecot());
        files.addAll(renderOpenDkim());
        boolean reloaded = reloadMail();
        // Keep Radicale's user list (calendar/contacts login) in step with the
        // mailbox list — same bcrypt hash, so one password everywhere.
        try { if (radicale.isInstalled()) radicale.syncUsers(); }
        catch (Exception e) { LOG.warnf("Radicale user sync failed: %s", e.getMessage()); }
        return new Result(files, reloaded);
    }

    /** Re-render the Rspamd policy. */
    public Result syncAntispam() {
        List<String> files = renderRspamd();
        boolean reloaded = platform.isLinux()
                && platform.exec(15, "systemctl", "reload-or-restart", "rspamd");
        return new Result(files, reloaded);
    }

    /** For every Domain in our DB, write an nginx vhost that serves the
     *  RFC-8461 MTA-STS policy file at the required URL
     *  `https://mta-sts.<domain>/.well-known/mta-sts.txt`. Tries certbot to
     *  upgrade to HTTPS (silent failure — if DNS hasn't propagated yet, the
     *  next syncAll tick will retry). */
    private List<String> renderMtaStsNginx() {
        List<String> touched = new ArrayList<>();
        if (!platform.isLinux()) return touched;
        if (!platform.fileExists("/etc/nginx/sites-available")) return touched;

        boolean anyChanged = false;
        for (Domain d : Domain.<Domain>listAll()) {
            if (d.name == null || d.name.isBlank()) continue;
            String host = "mta-sts." + d.name;
            String confPath = "/etc/nginx/sites-available/ravix-mta-sts-" + d.name + ".conf";
            String linkPath = "/etc/nginx/sites-enabled/ravix-mta-sts-" + d.name + ".conf";
            String existing = platform.readFile(confPath).orElse("");

            // We always emit the plain HTTP vhost. certbot --nginx may extend
            // this file to add a 443 server block on its own; renderMtaStsNginx
            // only OVERWRITES when the HTTP-only block is missing, so we don't
            // clobber certbot's edits on re-run.
            boolean alreadyTouchedByCertbot = existing.contains("listen 443");
            String vhost =
                  "# Generated by Ravix — MTA-STS policy for " + d.name + "\n"
                + "server {\n"
                + "    listen 80;\n"
                + "    listen [::]:80;\n"
                + "    server_name " + host + ";\n"
                + "    # ACME challenge for certbot, in case TLS isn't issued yet\n"
                + "    location /.well-known/acme-challenge/ { root /var/www/html; }\n"
                + "    location = /.well-known/mta-sts.txt {\n"
                + "        proxy_pass http://127.0.0.1:8080/api/well-known/mta-sts/" + d.name + ";\n"
                + "        proxy_set_header Host $host;\n"
                + "    }\n"
                + "    location / { return 404; }\n"
                + "}\n";

            if (!alreadyTouchedByCertbot && !existing.equals(vhost)) {
                platform.writeGenerated(confPath, vhost);
                anyChanged = true;
            }
            if (!platform.fileExists(linkPath)) {
                platform.exec(5, "ln", "-sf", confPath, linkPath);
                anyChanged = true;
            }
            touched.add(confPath);
        }

        if (anyChanged && platform.exec(10, "nginx", "-t")) {
            platform.exec(10, "systemctl", "reload", "nginx");
        }

        // Best-effort: try to issue a TLS cert for each mta-sts subdomain.
        // Skipped silently if cert already exists, if DNS hasn't propagated,
        // or if port 80 is firewalled — the hourly sync retries.
        for (Domain d : Domain.<Domain>listAll()) {
            if (d.name == null || d.name.isBlank()) continue;
            String host = "mta-sts." + d.name;
            if (platform.fileExists("/etc/letsencrypt/live/" + host + "/fullchain.pem")) continue;
            // --register-unsafely-without-email: panel doesn't ask for one yet.
            //   --nginx: certbot rewrites the vhost in place to add a 443 server.
            //   --redirect: enforce HTTPS — receivers need it for MTA-STS anyway.
            //   --non-interactive --agree-tos: never prompt.
            boolean ok = platform.exec(120, "certbot", "--nginx",
                    "-d", host,
                    "--non-interactive", "--agree-tos",
                    "--redirect",
                    "--register-unsafely-without-email");
            if (ok) {
                LOG.infof("MTA-STS: TLS cert issued for %s", host);
            } else {
                LOG.warnf("MTA-STS: certbot for %s failed (will retry on next sync). " +
                          "Check DNS for %s and that port 80 is reachable.", host, host);
            }
        }
        return touched;
    }

    /** Bring `main.cf` + opendkim.conf into the shape Ravix expects.
     *  Idempotent — uses `postconf -e` so re-running is safe. Returns the set
     *  of files actually touched (only those that needed changes, kind of —
     *  postconf rewrites main.cf on every call, but we report it once). */
    private List<String> renderMailDaemons() {
        List<String> touched = new ArrayList<>();
        if (!platform.isLinux()) return touched;

        // 0. The mail-storage account + base dir. Dovecot delivers as this uid
        //    (mail_uid) and Radicale's unit runs as User=vmail — but the package
        //    install never creates the account, so without this BOTH break:
        //    inbound LMTP can't write the Maildir, and radicale.service fails to
        //    start ("user vmail not found"). Idempotent, runs every apply/boot.
        ensureMailStorage();
        // Make sure Postfix/Dovecot actually write /var/log/mail.log — Debian 12
        // minimal images log only to journald, leaving the Logs page (and any
        // mail-flow debugging) blind. One-time rsyslog install when absent.
        ensureMailLogging();

        // 1. Pick the mail hostname — must match the server's PTR so receivers
        //    (Gmail in particular) can do forward-confirm. Fall back to the
        //    actual hostname if the operator hasn't set one yet.
        AppSetting h = AppSetting.findById("hostname");
        String mailHost = h != null && h.value != null && !h.value.isBlank()
                ? h.value.trim() : platform.hostname();

        // 2. Postfix main.cf — milter wiring + hostname + IP family preference.
        //    inet:127.0.0.1:8891 (TCP) instead of unix-socket because Postfix
        //    runs chrooted under /var/spool/postfix and can't see /run/opendkim.
        platform.exec(10, "postconf", "-e", "myhostname = " + mailHost);
        platform.exec(10, "postconf", "-e", "smtp_helo_name = " + mailHost);
        platform.exec(10, "postconf", "-e", "milter_default_action = accept");
        platform.exec(10, "postconf", "-e", "milter_protocol = 6");
        platform.exec(10, "postconf", "-e", "smtpd_milters = inet:127.0.0.1:8891");
        platform.exec(10, "postconf", "-e", "non_smtpd_milters = inet:127.0.0.1:8891");
        platform.exec(10, "postconf", "-e", "inet_protocols = all");
        // Outbound-25 path: some hosters block IPv4 25 but leave IPv6 open
        // (and vice versa). Prefer IPv6 when present — the readiness check
        // will tell the operator which family actually reached the public
        // MXs; if it's IPv4-only that path still works under "any".
        platform.exec(10, "postconf", "-e", "smtp_address_preference = any");
        // Incoming delivery: hand virtual-domain mail to Dovecot over LMTP so
        // Dovecot creates the Maildir + special folders, applies the user's
        // Sieve rules, and keeps everything consistent with what IMAP shows.
        // WITHOUT this, virtual_transport stays at the package default
        // "error:..." and NO mail is ever delivered to any mailbox.
        platform.exec(10, "postconf", "-e",
                "virtual_transport = lmtp:unix:private/dovecot-lmtp");
        platform.exec(10, "postconf", "-e",
                "mailbox_transport = lmtp:unix:private/dovecot-lmtp");
        platform.exec(10, "postconf", "-e", "virtual_mailbox_base = " + vmailBase);
        // Wire the rendered virtual maps into Postfix and KEEP the managed mail
        // domains OUT of mydestination. Without this, a domain equal to
        // myhostname (e.g. the mail host == the mail domain) is treated as a
        // LOCAL destination, so inbound mail to its mailboxes is rejected with
        // "User unknown in local recipient table" — it never reaches the
        // virtual mailbox / Dovecot at all.
        platform.exec(10, "postconf", "-e", "mydestination = localhost");
        platform.exec(10, "postconf", "-e",
                "virtual_mailbox_domains = hash:" + postfixDir + "/virtual_domains");
        platform.exec(10, "postconf", "-e",
                "virtual_mailbox_maps = hash:" + postfixDir + "/virtual_mailboxes");
        platform.exec(10, "postconf", "-e",
                "virtual_alias_maps = hash:" + postfixDir + "/virtual_aliases");
        touched.add("/etc/postfix/main.cf");
        // Dovecot delivery + namespace + LMTP socket in Postfix's chroot.
        touched.addAll(renderDovecotDelivery(mailHost));

        // 3. OpenDKIM — switch the daemon to TCP, point at KeyTable +
        //    SigningTable so it actually *signs* (out of the box, opendkim
        //    runs verify-only — no signing without those directives), and
        //    make sure the chrooted Postfix can reach the socket. Default
        //    Debian package ships with a unix socket in /run/opendkim/
        //    that the chrooted Postfix can't see — hence TCP on 8891.
        boolean confChanged = false;
        if (platform.fileExists("/etc/opendkim.conf")) {
            String orig = platform.readFile("/etc/opendkim.conf").orElse("");
            // Required signing directives. Lines we want to be PRESENT and
            // un-commented exactly as below.
            String[] want = {
                    "Socket                  inet:8891@127.0.0.1",
                    "KeyTable                refile:/etc/opendkim/KeyTable",
                    "SigningTable            refile:/etc/opendkim/SigningTable",
                    "ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts",
                    "InternalHosts           refile:/etc/opendkim/TrustedHosts",
                    "Mode                    sv",
                    "AutoRestart             yes",
                    "AutoRestartRate         10/1h",
            };
            String patched = orig;
            for (String line : want) {
                String key = line.split("\\s+")[0];
                // Replace existing line (commented or not) with our version.
                String regex = "(?m)^#?\\s*" + java.util.regex.Pattern.quote(key) + "\\b.*$";
                if (patched.matches("(?s).*" + regex + ".*")) {
                    patched = patched.replaceAll(regex, java.util.regex.Matcher.quoteReplacement(line));
                } else {
                    patched += "\n" + line + "\n";
                }
            }
            if (!patched.equals(orig)) {
                platform.writeGenerated("/etc/opendkim.conf", patched);
                confChanged = true;
            }
            touched.add("/etc/opendkim.conf");
        }
        // /etc/default/opendkim — only need to set SOCKET so the daemon
        // listens on TCP on boot (the conf above is the runtime authority,
        // but Debian's init script reads this file too).
        if (platform.fileExists("/etc/default/opendkim")) {
            String orig = platform.readFile("/etc/default/opendkim").orElse("");
            String patched = orig.replaceAll("(?m)^SOCKET=.*$",
                    "SOCKET=\"inet:8891@127.0.0.1\"");
            if (!patched.contains("SOCKET=")) {
                patched = patched + "\nSOCKET=\"inet:8891@127.0.0.1\"\n";
            }
            if (!patched.equals(orig)) {
                platform.writeGenerated("/etc/default/opendkim", patched);
                confChanged = true;
            }
            touched.add("/etc/default/opendkim");
        }
        // Ensure TrustedHosts has loopback so opendkim treats locally-
        // submitted mail as "internal" → sign instead of just verify.
        // Without this entry, OpenDKIM's default Mode=v applies and
        // DKIM-Signature is never added.
        String trusted = "/etc/opendkim/TrustedHosts";
        String trustedBody = platform.readFile(trusted).orElse("");
        StringBuilder needed = new StringBuilder(trustedBody);
        for (String host : new String[]{"127.0.0.1", "::1", "localhost"}) {
            if (!trustedBody.contains(host)) {
                needed.append(host).append('\n');
            }
        }
        if (!needed.toString().equals(trustedBody)) {
            platform.writeGenerated(trusted, needed.toString());
            confChanged = true;
            touched.add(trusted);
        }
        if (confChanged) {
            platform.exec(15, "systemctl", "restart", "opendkim");
        }

        // 4. Mail-host TLS cert (separate from the mta-sts.<host> cert) so
        //    Postfix/Dovecot serve a real Let's Encrypt cert on port 25/465/
        //    587/993, and DANE/TLSA can pin its SPKI hash. Issue once;
        //    certbot.timer renews automatically every 60 days.
        touched.addAll(ensureMailHostCert(mailHost));

        // 5. Wire the cert into Postfix (smtpd_tls_* + smtp_tls_*) so the
        //    receivers' TLSA validation matches what Postfix actually presents.
        wirePostfixCert(mailHost);

        // 6. Install a certbot deploy-hook so that after every successful
        //    renewal we recompute the TLSA hash and push it to Cloudflare —
        //    otherwise DANE breaks on the day a renewed cert lands.
        installRenewalHook();
        return touched;
    }

    /** Issue a Let's Encrypt cert for the mail hostname itself (not just
     *  mta-sts.<host>). Uses --webroot via /var/www/html which the panel's
     *  main nginx vhost serves. Idempotent — skipped when cert already on disk. */
    private List<String> ensureMailHostCert(String mailHost) {
        List<String> touched = new ArrayList<>();
        if (mailHost == null || mailHost.isBlank()) return touched;
        String certPath = "/etc/letsencrypt/live/" + mailHost + "/fullchain.pem";
        if (platform.fileExists(certPath)) return touched;

        // Ensure /var/www/html exists and that the panel's main nginx vhost
        // serves /.well-known/acme-challenge/ from it. The vhost was written
        // by install.sh without an ACME location — patch it once here.
        platform.exec(5, "mkdir", "-p", "/var/www/html/.well-known/acme-challenge");
        patchMainNginxForAcme();

        // certonly --webroot writes the cert files but doesn't touch nginx.
        // We deliberately don't use --nginx here — the panel's main vhost
        // is doing other things and we don't want certbot to rewrite it
        // with HTTPS server blocks pointing at the wrong root.
        boolean ok = platform.exec(180, "certbot", "certonly",
                "--webroot", "-w", "/var/www/html",
                "-d", mailHost,
                "--non-interactive", "--agree-tos",
                "--register-unsafely-without-email",
                "--keep-until-expiring");
        if (ok && platform.fileExists(certPath)) {
            LOG.infof("Mail host: TLS cert issued for %s", mailHost);
            touched.add(certPath);
        } else {
            LOG.warnf("Mail host: certbot for %s failed (will retry on next sync). " +
                      "Check DNS A/AAAA for %s and that port 80 is reachable.",
                    mailHost, mailHost);
        }
        return touched;
    }

    /** Ensure the ACME HTTP-01 webroot exists and the panel's nginx vhost
     *  serves it. Public so the user-facing certificate issuance (CertService)
     *  can guarantee the same challenge path certbot --webroot relies on. */
    public void ensureAcmeWebroot() {
        platform.exec(5, "mkdir", "-p", "/var/www/html/.well-known/acme-challenge");
        patchMainNginxForAcme();
    }

    /** Add a location /.well-known/acme-challenge/ to the panel's main nginx
     *  vhost so certbot --webroot works for the mail host. Idempotent. */
    private void patchMainNginxForAcme() {
        String confPath = "/etc/nginx/sites-available/ravix";
        if (!platform.fileExists(confPath)) return;
        String orig = platform.readFile(confPath).orElse("");
        if (orig.contains(".well-known/acme-challenge")) return; // already patched
        // Insert before the catch-all location / block.
        String acme =
              "    # Added by Ravix: ACME HTTP-01 challenge for certbot --webroot.\n"
            + "    location ^~ /.well-known/acme-challenge/ {\n"
            + "        root /var/www/html;\n"
            + "        default_type \"text/plain\";\n"
            + "        try_files $uri =404;\n"
            + "    }\n";
        // quoteReplacement: the ACME block contains "$uri", which replaceFirst
        // would otherwise treat as a group reference ("Illegal group reference").
        String patched = orig.replaceFirst("(?m)^    location / \\{",
                java.util.regex.Matcher.quoteReplacement(acme + "    location / {"));
        if (patched.equals(orig)) return; // pattern not found, leave it alone
        platform.writeGenerated(confPath, patched);
        if (platform.exec(10, "nginx", "-t")) {
            platform.exec(10, "systemctl", "reload", "nginx");
            LOG.infof("Patched %s with ACME challenge location", confPath);
        }
    }

    /** Point Postfix at the mail-host cert so its TLS handshake offers a
     *  trustable cert whose SPKI matches the published TLSA hash. */
    private void wirePostfixCert(String mailHost) {
        String certPath = "/etc/letsencrypt/live/" + mailHost + "/fullchain.pem";
        String keyPath  = "/etc/letsencrypt/live/" + mailHost + "/privkey.pem";
        if (!platform.fileExists(certPath) || !platform.fileExists(keyPath)) {
            return; // cert not issued yet; next sync tick will try again
        }
        platform.exec(10, "postconf", "-e", "smtpd_tls_cert_file = " + certPath);
        platform.exec(10, "postconf", "-e", "smtpd_tls_key_file = "  + keyPath);
        platform.exec(10, "postconf", "-e", "smtp_tls_cert_file = "  + certPath);
        platform.exec(10, "postconf", "-e", "smtp_tls_key_file = "   + keyPath);
        platform.exec(10, "postconf", "-e", "smtpd_tls_security_level = may");
        platform.exec(10, "postconf", "-e", "smtp_tls_security_level = may");
        // Required for DANE-EE pinning: tlsa_only validation is too strict for
        // generic outbound; "dane" tries DANE first, falls back to PKIX/may.
        platform.exec(10, "postconf", "-e", "smtp_dns_support_level = dnssec");
        platform.exec(10, "postconf", "-e", "smtp_tls_security_level = dane");
        // Reload so the new cert is picked up. Soft reload (not restart)
        // so in-flight deliveries aren't dropped.
        platform.exec(10, "postfix", "reload");
    }

    /** Drop a shell script under /etc/letsencrypt/renewal-hooks/deploy/ that
     *  certbot runs after every successful renew. The script tells the
     *  Ravix backend to recompute the TLSA hash and push it to Cloudflare —
     *  otherwise DANE-validating receivers reject mail on renewal day. */
    private void installRenewalHook() {
        String hookDir = "/etc/letsencrypt/renewal-hooks/deploy";
        String hookPath = hookDir + "/ravix-tlsa-update.sh";
        if (!platform.fileExists("/etc/letsencrypt")) return;
        platform.exec(5, "mkdir", "-p", hookDir);
        String body =
              "#!/bin/bash\n"
            + "# Generated by Ravix — re-publish DANE TLSA after cert renewal.\n"
            + "# certbot sets RENEWED_LINEAGE to the live dir, e.g.\n"
            + "#   /etc/letsencrypt/live/ravix.example.com\n"
            + "# We POST to the panel's internal endpoint which recomputes the hash\n"
            + "# and pushes a CF update.\n"
            + "exec curl -fsS -X POST --max-time 30 \\\n"
            + "  http://127.0.0.1:8080/api/internal/cert-renewed \\\n"
            + "  -H \"X-Ravix-Hook: 1\" \\\n"
            + "  --data-urlencode \"lineage=${RENEWED_LINEAGE:-}\" >/dev/null\n";
        String existing = platform.readFile(hookPath).orElse("");
        if (!existing.equals(body)) {
            platform.writeGenerated(hookPath, body);
            platform.exec(5, "chmod", "+x", hookPath);
        }
    }

    /** On every Quarkus boot AND every hour after: re-render local configs
     *  (nginx MTA-STS vhost, opendkim, postfix milter wiring, …) AND push
     *  the CF plan. A deploy retro-fits any pre-existing domain without
     *  the operator clicking anything.
     *
     *  Implemented via the scheduler (not StartupEvent) because the
     *  scheduler runs each tick inside a managed transactional context —
     *  raw startup threads have no JPA Session and {@code Domain.listAll}
     *  throws. delay=15s lets the REST listener finish binding first.
     */
    @io.quarkus.scheduler.Scheduled(
            every = "1h",
            delay = 15,
            delayUnit = java.util.concurrent.TimeUnit.SECONDS,
            concurrentExecution = io.quarkus.scheduler.Scheduled.ConcurrentExecution.SKIP)
    void scheduledFullSync() {
        try {
            Result r = syncAll();
            LOG.infof("Scheduled syncAll done — %d files, reloaded=%s",
                    r.files().size(), r.reloaded());
        } catch (Exception e) {
            LOG.warnf("Scheduled syncAll failed: %s", e.getMessage());
        }
    }

    /** Seed the panel/CLI catalogue of packages we expect installed and
     *  health-check commands we want to surface on /system. Pre-populates the
     *  rows so the SystemPage doesn't render blank "Статус пакетов: пусто"
     *  immediately after install; subsequent SystemResource calls update them
     *  live via dpkg-query / platform.run. */
    private void seedSystemCatalogues() {
        if (PackageStatus.count() == 0) {
            String[][] pkgs = {
                    {"postfix", "Mail transfer agent"},
                    {"dovecot-imapd", "IMAP server"},
                    {"opendkim", "DKIM signing"},
                    {"rspamd", "Spam filter"},
                    {"redis-server", "Rspamd backend"},
                    {"certbot", "Let's Encrypt"},
                    {"nginx", "HTTP frontend"},
                    {"postgresql", "Database"},
                    {"fail2ban", "Brute-force protection"},
            };
            int i = 0;
            for (String[] p : pkgs) {
                PackageStatus ps = new PackageStatus();
                ps.name = p[0];
                ps.version = "—";
                ps.status = "pending";
                ps.sortOrder = i++;
                ps.persist();
            }
            LOG.infof("Seeded %d package_status rows", pkgs.length);
        }
        if (CommandCheck.count() == 0) {
            String[] cmds = {
                    "postconf -d mydestination",
                    "postqueue -p",
                    "doveadm reload",
                    // Use Postfix's myhostname (set by Ravix to the mail
                    // hostname) instead of the OS hostname — that's the
                    // domain we actually publish DKIM under.
                    "opendkim-testkey -d $(postconf -h myhostname) -s ravix2026",
                    "systemctl is-active postfix",
                    "systemctl is-active dovecot",
                    "systemctl is-active opendkim",
                    "rspamadm configtest",
            };
            int i = 0;
            for (String c : cmds) {
                CommandCheck cc = new CommandCheck();
                cc.cmd = c;
                cc.result = "—";
                cc.ok = false;
                cc.sortOrder = i++;
                cc.persist();
            }
            LOG.infof("Seeded %d command_check rows", cmds.length);
        }
        // Pull installer log from /root/install.log (install.sh tees there).
        // We don't parse it line-by-line — we just want the operator to see
        // real artifacts of their install, not a hard-coded "1 min 02 s" stub.
        if (InstallLog.count() == 0) {
            java.nio.file.Path log = java.nio.file.Path.of("/root/install.log");
            if (java.nio.file.Files.isReadable(log)) {
                try {
                    java.util.List<String> lines = java.nio.file.Files.readAllLines(log);
                    int i = 0;
                    // Strip ANSI escapes and keep only the stage markers + done
                    // lines + the final summary. That's what the operator
                    // actually wants to see, not the entire 4-min mvn log.
                    java.util.regex.Pattern ansi = java.util.regex.Pattern.compile("\\u001b\\[[0-9;]*[mK]");
                    java.util.regex.Pattern keep = java.util.regex.Pattern.compile(
                            "^\\s*(▶|✓|✗|!|▸|Total time|Disk used|URL|Login|Password|Config)\\b.*");
                    for (String raw : lines) {
                        String clean = ansi.matcher(raw).replaceAll("").stripTrailing();
                        if (clean.isBlank()) continue;
                        if (!keep.matcher(clean).matches()) continue;
                        InstallLog il = new InstallLog();
                        il.atOffset = "+" + (i * 1) + "s"; // ordinal — install.sh doesn't stamp lines
                        il.message = clean;
                        il.ok = !clean.contains("✗") && !clean.toLowerCase().contains("error");
                        il.sortOrder = i++;
                        il.persist();
                    }
                    LOG.infof("Imported %d install_log lines from /root/install.log", i);
                } catch (Exception e) {
                    LOG.warnf("install.log import failed: %s", e.getMessage());
                }
            }
        }
    }

    /** Auto-bump AppSetting.version to "0.1.<git-commit-count>". The sidebar
     *  footer shows this, so the operator can tell at a glance whether a deploy
     *  actually landed. Runs at startup (every boot) AND in syncAll so it stays
     *  fresh even when the operator never clicks "Apply config". */
    @jakarta.transaction.Transactional
    public void bumpVersion() {
        try {
            String commitCount = platform.run(5, "git", "-C", "/opt/ravix/src", "rev-list", "--count", "HEAD")
                    .orElse("").trim();
            if (commitCount.matches("\\d+")) {
                AppSetting v = AppSetting.findById("version");
                String want = "0.1." + commitCount;
                if (v == null) { v = new AppSetting(); v.key = "version"; }
                if (!want.equals(v.value)) {
                    v.value = want;
                    v.persist();
                    LOG.infof("Version bumped to %s", want);
                }
            }
        } catch (Exception e) { /* dev machine without git, ignore */ }
    }

    void onStart(@jakarta.enterprise.event.Observes io.quarkus.runtime.StartupEvent ev) {
        bumpVersion();
        // Ensure the panel's nginx/TLS/fail2ban layout on every boot — migrates
        // an existing install onto the dedicated HTTPS port and self-heals drift.
        // Run it OFF the startup thread: it shells out to openssl, nginx -t /
        // reload, systemctl (fail2ban) and ufw, which would otherwise block the
        // HTTP port from opening and leave the panel unreachable for many
        // seconds after every restart. A graceful nginx reload doesn't drop the
        // already-running panel, so doing it a beat later is safe.
        Thread t = new Thread(() -> {
            try {
                renderPanelStack();
            } catch (Exception e) {
                LOG.warnf("Panel stack render at startup failed (non-fatal): %s", e.getMessage());
            }
        }, "ravix-panel-stack");
        t.setDaemon(true);
        t.start();
    }

    @jakarta.transaction.Transactional
    public Result syncAll() {
        bumpVersion();
        // Bootstrap: if the operator hasn't configured a mail hostname yet
        // (still on the OS default like "spb-3-vm-feuy"), promote the first
        // managed Domain to AppSetting.hostname. Otherwise DomainChecker's
        // PTR expectation diverges from what we actually publish and the
        // user sees a confusing "Внимание" badge on the domain page.
        AppSetting h = AppSetting.findById("hostname");
        boolean unset = h == null || h.value == null || h.value.isBlank()
                || h.value.equals(platform.hostname());
        if (unset) {
            Domain first = Domain.<Domain>find("order by createdAt asc").firstResult();
            if (first != null && first.name != null && !first.name.isBlank()) {
                if (h == null) { h = new AppSetting(); h.key = "hostname"; }
                h.value = first.name;
                h.persist();
                LOG.infof("Bootstrap: AppSetting.hostname set to %s (from first managed domain)", first.name);
            }
        }
        seedSystemCatalogues();
        List<String> files = new ArrayList<>();
        files.addAll(renderMailDaemons());
        files.addAll(renderPostfix());
        files.add(renderDovecot());
        files.addAll(renderOpenDkim());
        files.addAll(renderRspamd());
        // Panel itself: own the nginx vhost so it can never drift into a
        // broken/conflicting state. Panel on its own HTTPS port (self-signed by
        // default, Let's Encrypt when available); a dedicated :80 vhost serves
        // ACME challenges and redirects everything else to the panel.
        files.addAll(renderPanelStack());
        files.addAll(renderMtaStsNginx());
        // Expose CalDAV/CardDAV (Radicale) at /dav/ + keep its users synced.
        try {
            if (radicale.isInstalled()) {
                radicale.syncUsers();
                files.addAll(radicale.renderNginx());
            }
        } catch (Exception e) {
            LOG.warnf("Radicale provisioning failed: %s", e.getMessage());
        }
        boolean reloaded = reloadMail();
        // If a Cloudflare token is configured, push the current DNS plan for
        // every domain whose zone the token can see. Silent no-op otherwise —
        // we never want a missing CF integration to fail Apply config.
        try {
            int n = cloudflare.autoSyncAll();
            if (n > 0) LOG.infof("Cloudflare DNS re-synced for %d domain(s) after Apply config", n);
        } catch (Exception e) {
            LOG.warnf("Cloudflare auto-sync failed (ignored): %s", e.getMessage());
        }
        if (platform.isLinux()) {
            platform.exec(15, "systemctl", "reload-or-restart", "rspamd");
        }
        return new Result(files, reloaded);
    }

    // --- Panel nginx + TLS + fail2ban (self-healing) ----------------------

    /** Render the panel's own nginx: an HTTPS vhost on the dedicated panel port
     *  (self-signed cert by default, Let's Encrypt when present) plus a separate
     *  :80 vhost that serves ACME challenges and redirects everything else to
     *  the panel. Owning this here means it can never drift into a broken or
     *  cert-conflicting state — every Apply config restores the known-good
     *  layout. */
    /** Re-render the panel vhost so it picks up a freshly issued Let's Encrypt
     *  cert (or falls back to self-signed). Safe to call from the cert task. */
    public void refreshPanelTls() {
        renderPanelStack();
    }

    private List<String> renderPanelStack() {
        List<String> touched = new ArrayList<>();
        if (!platform.isLinux() || !platform.fileExists("/etc/nginx/sites-available")) return touched;

        String host = panelHostname();
        String leCert = "/etc/letsencrypt/live/" + host + "/fullchain.pem";
        String leKey = "/etc/letsencrypt/live/" + host + "/privkey.pem";

        ensureSelfSigned(host);
        // Only ever reference a cert whose key actually matches it — a broken
        // pair makes nginx fail the TLS handshake (IP access dies with no
        // response). The default (IP / no-SNI) vhost prefers the bypassable
        // self-signed cert; if that's unusable it falls back to the LE cert
        // (still valid — just a host-mismatch warning, never a hard failure).
        boolean selfOk = certKeyValid(SSL_DIR + "/panel.crt", SSL_DIR + "/panel.key");
        boolean haveLe = certKeyValid(leCert, leKey);
        String defCert = selfOk ? SSL_DIR + "/panel.crt" : (haveLe ? leCert : null);
        String defKey  = selfOk ? SSL_DIR + "/panel.key" : (haveLe ? leKey  : null);
        if (defCert == null) {
            LOG.warn("Panel: no usable TLS cert (self-signed and LE both invalid) — "
                    + "leaving the nginx config untouched so the panel stays reachable.");
            return touched;
        }

        // Shared panel body, included by each cert-specific server block.
        String body = ""
            + "    access_log /var/log/nginx/ravix-panel.access.log;\n"
            + "    root " + WEB_DIR + ";\n"
            + "    index index.html;\n"
            + "    client_max_body_size 50m;\n"
            + "    location /api/ {\n"
            + "        proxy_pass http://127.0.0.1:" + backendPort + ";\n"
            + "        proxy_set_header Host $host;\n"
            + "        proxy_set_header X-Real-IP $remote_addr;\n"
            + "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
            + "        proxy_set_header X-Forwarded-Proto $scheme;\n"
            + "    }\n"
            + "    location ~* \\.(js|css|woff2?|svg|png|jpg|jpeg|gif|ico)$ {\n"
            + "        expires 1y; access_log off;\n"
            + "        add_header Cache-Control \"public, max-age=31536000, immutable\";\n"
            + "    }\n"
            + "    location = /index.html {\n"
            + "        add_header Cache-Control \"no-cache, no-store, must-revalidate\"; expires off;\n"
            + "    }\n"
            + "    location / { try_files $uri $uri/ /index.html; }\n";

        StringBuilder pb = new StringBuilder();
        pb.append("# Generated by Ravix — panel (HTTPS on port ").append(panelPort).append("). Do not edit.\n");
        // Default vhost (IP / no-SNI / any host) — self-signed, bypassable everywhere.
        pb.append("server {\n")
          .append("    listen ").append(panelPort).append(" ssl default_server;\n")
          .append("    listen [::]:").append(panelPort).append(" ssl default_server;\n")
          .append("    server_name _;\n")
          .append("    ssl_certificate ").append(defCert).append(";\n")
          .append("    ssl_certificate_key ").append(defKey).append(";\n")
          .append("    ssl_protocols TLSv1.2 TLSv1.3;\n")
          .append(body)
          .append("}\n");
        // Hostname vhost — real Let's Encrypt cert (clean, no browser warning).
        if (haveLe && !leCert.equals(defCert)) {
            pb.append("server {\n")
              .append("    listen ").append(panelPort).append(" ssl;\n")
              .append("    listen [::]:").append(panelPort).append(" ssl;\n")
              .append("    server_name ").append(host).append(";\n")
              .append("    ssl_certificate ").append(leCert).append(";\n")
              .append("    ssl_certificate_key ").append(leKey).append(";\n")
              .append("    ssl_protocols TLSv1.2 TLSv1.3;\n")
              .append(body)
              .append("}\n");
        }
        String panel = pb.toString();

        String acme = ""
            + "# Generated by Ravix — ACME HTTP-01 + redirect to the panel. Do not edit.\n"
            + "server {\n"
            + "    listen 80 default_server;\n"
            + "    listen [::]:80 default_server;\n"
            + "    server_name _;\n"
            + "    location ^~ /.well-known/acme-challenge/ {\n"
            + "        root /var/www/html;\n"
            + "        default_type \"text/plain\";\n"
            + "        try_files $uri =404;\n"
            + "    }\n"
            + "    location / { return 301 https://$host:" + panelPort + "$request_uri; }\n"
            + "}\n";

        platform.exec(5, "mkdir", "-p", "/var/www/html/.well-known/acme-challenge");
        writeIfChanged("/etc/nginx/sites-available/ravix", panel, touched);
        writeIfChanged("/etc/nginx/sites-available/ravix-acme", acme, touched);
        platform.exec(5, "ln", "-sf", "/etc/nginx/sites-available/ravix", "/etc/nginx/sites-enabled/ravix");
        platform.exec(5, "ln", "-sf", "/etc/nginx/sites-available/ravix-acme", "/etc/nginx/sites-enabled/ravix-acme");
        platform.exec(5, "rm", "-f", "/etc/nginx/sites-enabled/default");
        if (platform.exec(10, "nginx", "-t")) {
            platform.exec(10, "systemctl", "reload", "nginx");
        }

        ensureFail2banPanel();
        platform.exec(5, "bash", "-c",
                "command -v ufw >/dev/null && ufw allow " + panelPort + "/tcp >/dev/null 2>&1 || true");
        return touched;
    }

    private String panelHostname() {
        String host = null;
        try {
            // Wrap the read in its own transaction so it also works from the
            // background startup thread (no ambient request/tx context there).
            host = io.quarkus.narayana.jta.QuarkusTransaction.requiringNew().call(() -> {
                AppSetting h = AppSetting.findById("hostname");
                return h != null && h.value != null && !h.value.isBlank() ? h.value : null;
            });
        } catch (Exception ignore) {
            // Fall back to the OS host if the lookup isn't possible.
        }
        if (host == null || host.isBlank()) host = platform.hostname();
        return host == null || host.isBlank() ? "localhost" : host;
    }

    /** True only when cert+key both exist, are non-empty, and the key actually
     *  matches the certificate (same public key). A mismatched/partial pair
     *  makes nginx fail the TLS handshake. */
    private boolean certKeyValid(String cert, String key) {
        if (!platform.fileExists(cert) || !platform.fileExists(key)) return false;
        return platform.run(6, "bash", "-c",
                "test -s '" + cert + "' && test -s '" + key + "' && "
              + "[ \"$(openssl x509 -in '" + cert + "' -noout -pubkey 2>/dev/null)\" = "
              + "\"$(openssl pkey -in '" + key + "' -pubout 2>/dev/null)\" ] && echo ok")
                .orElse("").contains("ok");
    }

    private void ensureSelfSigned(String host) {
        if (certKeyValid(SSL_DIR + "/panel.crt", SSL_DIR + "/panel.key")) return;

        // SAN: hostname + the primary IPv4 only — IPv6 / scoped / docker
        // addresses from `hostname -I` can yield a cert that breaks TLS.
        String ip4 = platform.run(3, "bash", "-c",
                "hostname -I 2>/dev/null | tr ' ' '\\n' | grep -E '^[0-9]+(\\.[0-9]+){3}$' | head -1")
                .orElse("").trim();
        String san = "subjectAltName=DNS:" + host + (ip4.isBlank() ? "" : ",IP:" + ip4);

        platform.exec(5, "mkdir", "-p", SSL_DIR);
        // Generate to temp files and install ONLY if the new pair verifies — so
        // a failed openssl run can never leave a broken cert in place.
        boolean ok = platform.exec(40, "bash", "-c",
                "openssl req -x509 -newkey rsa:2048 -nodes -days 825 "
              + "-keyout " + SSL_DIR + "/panel.key.tmp -out " + SSL_DIR + "/panel.crt.tmp "
              + "-subj '/CN=" + host + "' -addext '" + san + "' >/dev/null 2>&1 "
              + "&& [ \"$(openssl x509 -in " + SSL_DIR + "/panel.crt.tmp -noout -pubkey 2>/dev/null)\" = "
              + "\"$(openssl pkey -in " + SSL_DIR + "/panel.key.tmp -pubout 2>/dev/null)\" ]");
        if (ok) {
            platform.exec(5, "bash", "-c",
                    "mv -f " + SSL_DIR + "/panel.crt.tmp " + SSL_DIR + "/panel.crt && "
                  + "mv -f " + SSL_DIR + "/panel.key.tmp " + SSL_DIR + "/panel.key && "
                  + "chmod 600 " + SSL_DIR + "/panel.key");
        } else {
            platform.exec(5, "bash", "-c",
                    "rm -f " + SSL_DIR + "/panel.crt.tmp " + SSL_DIR + "/panel.key.tmp");
            LOG.warn("Panel: self-signed cert generation failed; the panel will fall "
                    + "back to the Let's Encrypt cert for IP access if available.");
        }
    }

    /** fail2ban jail that bans IPs brute-forcing the panel login. */
    private void ensureFail2banPanel() {
        if (!platform.fileExists("/etc/fail2ban")) return;
        String filter = ""
            + "[Definition]\n"
            + "failregex = ^<HOST> .*\"POST /api/auth/login HTTP/[^\"]+\" 401\n"
            + "ignoreregex =\n";
        String jail = ""
            + "[ravix-panel]\n"
            + "enabled = true\n"
            // Read the nginx access log file directly. Without this the jail
            // would inherit a systemd-journal backend and silently ignore
            // logpath, so brute-force on the panel would never be detected.
            + "backend = polling\n"
            + "port = " + panelPort + "\n"
            + "filter = ravix-panel\n"
            + "logpath = /var/log/nginx/ravix-panel.access.log\n"
            + "maxretry = 5\n"
            + "findtime = 600\n"
            + "bantime = 3600\n";
        boolean changed =
                !filter.equals(platform.readFile("/etc/fail2ban/filter.d/ravix-panel.conf").orElse(""))
              | !jail.equals(platform.readFile("/etc/fail2ban/jail.d/ravix-panel.local").orElse(""));
        platform.writeGenerated("/etc/fail2ban/filter.d/ravix-panel.conf", filter);
        platform.writeGenerated("/etc/fail2ban/jail.d/ravix-panel.local", jail);
        platform.exec(5, "bash", "-c", "touch /var/log/nginx/ravix-panel.access.log");
        if (changed) platform.exec(15, "systemctl", "reload-or-restart", "fail2ban");
    }

    private void writeIfChanged(String path, String content, List<String> touched) {
        if (!content.equals(platform.readFile(path).orElse(""))) {
            platform.writeGenerated(path, content);
            touched.add(path);
        }
    }

    // --- Postfix virtual maps ---------------------------------------------

    List<String> renderPostfix() {   // package-private for golden tests
        StringBuilder domains = new StringBuilder();
        for (Domain d : Domain.<Domain>listAll()) {
            domains.append(d.name).append(" OK\n");
        }

        StringBuilder boxes = new StringBuilder();
        for (Mailbox m : Mailbox.<Mailbox>list("status", "active")) {
            String local = localPart(m.email);
            boxes.append(m.email).append(' ')
                 .append(m.domain).append('/').append(local).append("/\n");
        }

        StringBuilder aliases = new StringBuilder();
        for (Alias a : Alias.<Alias>list("status", "active")) {
            if (a.destinations == null || a.destinations.isEmpty()) continue;
            String src = a.catchAll ? "@" + a.domain : a.source;
            aliases.append(src).append(' ')
                   .append(String.join(",", a.destinations)).append('\n');
        }

        String fDomains = postfixDir + "/virtual_domains";
        String fBoxes = postfixDir + "/virtual_mailboxes";
        String fAliases = postfixDir + "/virtual_aliases";
        platform.writeGenerated(fDomains, domains.toString());
        platform.writeGenerated(fBoxes, boxes.toString());
        platform.writeGenerated(fAliases, aliases.toString());

        if (platform.isLinux()) {
            platform.exec(20, "postmap", "hash:" + fDomains);
            platform.exec(20, "postmap", "hash:" + fBoxes);
            platform.exec(20, "postmap", "hash:" + fAliases);
        }
        return List.of(fDomains, fBoxes, fAliases);
    }

    /** Write Dovecot's delivery + namespace config so incoming LMTP mail lands
     *  in each user's Maildir with the standard special folders, our virtual
     *  passwd-file is the auth source, and Sieve runs at delivery. Idempotent:
     *  only restarts Dovecot when the rendered file actually changed. */
    List<String> renderDovecotDelivery(String mailHost) {   // package-private for golden tests
        List<String> touched = new ArrayList<>();
        if (!platform.isLinux()) return touched;
        String confPath = "/etc/dovecot/conf.d/99-ravix.conf";
        String certDir = "/etc/letsencrypt/live/" + mailHost;
        boolean haveCert = platform.fileExists(certDir + "/fullchain.pem");

        StringBuilder c = new StringBuilder();
        c.append("# Generated by Ravix — do not edit by hand.\n");
        c.append("protocols = imap pop3 lmtp\n");
        c.append("mail_location = maildir:~/Maildir\n");
        c.append("mail_uid = ").append(vmailUid).append("\n");
        c.append("mail_gid = ").append(vmailGid).append("\n");
        c.append("first_valid_uid = ").append(vmailUid).append("\n");
        c.append("mail_privileged_group = ").append(vmailGid).append("\n\n");

        // Virtual users come from the passwd-file Ravix renders.
        c.append("passdb {\n");
        c.append("  driver = passwd-file\n");
        c.append("  args = scheme=BLF-CRYPT username_format=%u ").append(dovecotUserfile).append("\n");
        c.append("}\n");
        c.append("userdb {\n");
        c.append("  driver = passwd-file\n");
        c.append("  args = username_format=%u ").append(dovecotUserfile).append("\n");
        c.append("  default_fields = uid=").append(vmailUid)
         .append(" gid=").append(vmailGid)
         .append(" home=").append(vmailBase).append("/%d/%n\n");
        c.append("}\n\n");

        // LMTP listener Postfix can reach from its chroot.
        c.append("service lmtp {\n");
        c.append("  unix_listener /var/spool/postfix/private/dovecot-lmtp {\n");
        c.append("    mode = 0600\n    user = postfix\n    group = postfix\n");
        c.append("  }\n}\n\n");

        // Standard special-use mailboxes, auto-created and subscribed.
        c.append("namespace inbox {\n");
        c.append("  inbox = yes\n");
        for (String[] mb : new String[][]{
                {"Sent", "\\Sent"}, {"Drafts", "\\Drafts"}, {"Junk", "\\Junk"},
                {"Trash", "\\Trash"}, {"Archive", "\\Archive"}}) {
            c.append("  mailbox ").append(mb[0]).append(" {\n");
            c.append("    special_use = ").append(mb[1]).append("\n");
            c.append("    auto = subscribe\n");
            c.append("  }\n");
        }
        c.append("}\n\n");

        // Sieve at delivery time (Pigeonhole).
        c.append("protocol lmtp {\n  mail_plugins = $mail_plugins sieve\n}\n");
        c.append("plugin {\n  sieve = file:~/sieve;active=~/.dovecot.sieve\n}\n\n");

        if (haveCert) {
            c.append("ssl = yes\n");
            c.append("ssl_cert = <").append(certDir).append("/fullchain.pem\n");
            c.append("ssl_key = <").append(certDir).append("/privkey.pem\n");
        }

        String desired = c.toString();
        String existing = platform.readFile(confPath).orElse("");
        if (!desired.equals(existing)) {
            platform.writeGenerated(confPath, desired);
            platform.exec(15, "systemctl", "restart", "dovecot");
        }
        touched.add(confPath);
        return touched;
    }

    // --- Dovecot passwd-file ----------------------------------------------

    String renderDovecot() {   // package-private for golden tests
        StringBuilder sb = new StringBuilder();
        for (Mailbox m : Mailbox.<Mailbox>list("status", "active")) {
            String home = vmailBase + "/" + m.domain + "/" + localPart(m.email);
            // The passwd-file is BOTH passdb and userdb. A box WITHOUT a password
            // must still appear here, otherwise the userdb lookup fails and
            // inbound LMTP is rejected with "user doesn't exist" — the box can
            // never receive mail until a password is set. Emit an EMPTY password
            // field instead: Dovecot then denies IMAP/POP login (no credential to
            // verify) but the userdb entry still resolves the home + Maildir, so
            // delivery works and the mail shows in webmail. Set a password later
            // to enable IMAP/POP.
            String pw = (m.passwordHash == null || m.passwordHash.isBlank())
                    ? "" : "{BLF-CRYPT}" + m.passwordHash;
            // user:[{scheme}hash]:uid:gid::home::userdb_mail=maildir:home/Maildir
            sb.append(m.email).append(':').append(pw)
              .append(':').append(vmailUid).append(':').append(vmailGid)
              .append("::").append(home)
              .append("::userdb_mail=maildir:").append(home).append("/Maildir\n");
        }
        platform.writeGenerated(dovecotUserfile, sb.toString());
        return dovecotUserfile;
    }

    /**
     * Ensure the {@code vmail} group + user (uid/gid from config, default 5000)
     * exist and the mail-storage base dir is present and owned by them, then
     * pre-create each active mailbox's Maildir. Dovecot LMTP delivers as this
     * uid and Radicale's systemd unit runs as this user; neither the mail
     * packages nor the installer create the account, so this is the single
     * place that guarantees it. Fully idempotent — safe on every apply/boot.
     */
    void ensureMailStorage() {
        if (!platform.isLinux()) return;
        // Group + user. getent guard makes re-creation a no-op; we don't force
        // the uid/gid if the account already exists with a different one.
        platform.exec(5, "bash", "-c",
                "getent group vmail >/dev/null 2>&1 || groupadd -g " + vmailGid + " vmail");
        platform.exec(5, "bash", "-c",
                "getent passwd vmail >/dev/null 2>&1 || useradd -r -g vmail -u " + vmailUid
                        + " -d " + vmailBase + " -s /usr/sbin/nologin vmail");
        // Base dir — setgid (2770) so sub-dirs inherit the vmail group.
        platform.exec(5, "mkdir", "-p", vmailBase);
        platform.exec(5, "chown", "vmail:vmail", vmailBase);
        platform.exec(5, "chmod", "2770", vmailBase);
        // Pre-create each active mailbox's Maildir skeleton so inbound LMTP and
        // the webmail reader never race on a missing directory. Dovecot would
        // auto-create on first delivery, but doing it here means the folder is
        // visible immediately and ownership is guaranteed correct.
        for (Mailbox m : Mailbox.<Mailbox>list("status", "active")) {
            String home = vmailBase + "/" + m.domain + "/" + localPart(m.email);
            platform.exec(5, "mkdir", "-p",
                    home + "/Maildir/new", home + "/Maildir/cur", home + "/Maildir/tmp");
        }
        // One recursive chown of the whole tree — cheap and self-healing if a
        // box was created by root earlier (e.g. before vmail existed).
        platform.exec(20, "chown", "-R", "vmail:vmail", vmailBase);
    }

    /**
     * Ensure traditional syslog files (notably {@code /var/log/mail.log}) exist.
     * Debian 12 minimal images run journald only, so Postfix/Dovecot output
     * never reaches a file and the Logs page falls back to stale seed rows.
     * Installs rsyslog — whose shipped rules already route {@code mail.*} to
     * {@code /var/log/mail.log} — exactly once (guarded on the binary being
     * absent), so this is a no-op on every subsequent boot.
     */
    void ensureMailLogging() {
        if (!platform.isLinux()) return;
        if (!platform.run(3, "which", "rsyslogd").isEmpty()) return; // already present
        if (platform.fileExists("/var/log/mail.log")) return;        // logging already works
        platform.runEnv(180, java.util.Map.of("DEBIAN_FRONTEND", "noninteractive"),
                "apt-get", "install", "-y", "rsyslog");
        platform.exec(10, "systemctl", "enable", "--now", "rsyslog");
    }

    // --- OpenDKIM key + signing tables ------------------------------------

    private List<String> renderOpenDkim() {
        StringBuilder keyTable = new StringBuilder();
        StringBuilder signTable = new StringBuilder();
        List<String> written = new ArrayList<>();

        for (Domain d : Domain.<Domain>listAll()) {
            if (d.dkimPrivateKey == null || d.dkimPrivateKey.isBlank()) continue;
            String keyPath = dkimDir + "/keys/" + d.name + "/" + d.dkimSelector + ".private";
            platform.writeGenerated(keyPath, d.dkimPrivateKey);
            if (platform.isLinux()) {
                platform.exec(5, "chmod", "600", keyPath);
                platform.exec(5, "chown", "opendkim:opendkim", keyPath);
            }
            written.add(keyPath);
            keyTable.append(d.dkimSelector).append("._domainkey.").append(d.name)
                    .append(' ').append(d.name).append(':').append(d.dkimSelector)
                    .append(':').append(keyPath).append('\n');
            signTable.append("*@").append(d.name).append(' ')
                     .append(d.dkimSelector).append("._domainkey.").append(d.name).append('\n');
        }

        String fKey = dkimDir + "/KeyTable";
        String fSign = dkimDir + "/SigningTable";
        platform.writeGenerated(fKey, keyTable.toString());
        platform.writeGenerated(fSign, signTable.toString());
        written.add(fKey);
        written.add(fSign);
        return written;
    }

    // --- Rspamd policy -----------------------------------------------------

    private List<String> renderRspamd() {
        AntispamSetting s = AntispamSetting.findById(1);
        BigDecimal reject = s != null ? s.rejectThreshold : new BigDecimal("15.0");
        BigDecimal spam = s != null ? s.spamThreshold : new BigDecimal("6.0");
        BigDecimal greylist = spam.subtract(new BigDecimal("2"));
        boolean greyOn = s != null && s.greylisting;

        // Files under /etc/rspamd/local.d are merged INTO the matching
        // top-level section by rspamd's UCL loader — they must contain the
        // section's BODY, not the section itself. Wrapping in another
        // "actions { ... }" produced nested actions { actions { ... } } at
        // load time and broke `rspamadm configtest`.
        String actions = "# Generated by Ravix — do not edit by hand\n"
                + "reject = " + reject + ";\n"
                + "add_header = " + spam + ";\n"
                + "greylist = " + greylist + ";\n";
        String greylistConf = "# Generated by Ravix\nenabled = " + greyOn + ";\n";
        // Point rspamd at the local Redis so Bayes and greylisting are backed by it.
        String redisConf = "# Generated by Ravix\nservers = \"127.0.0.1:6379\";\n";

        String fActions = rspamdDir + "/actions.conf";
        String fGrey = rspamdDir + "/greylist.conf";
        String fRedis = rspamdDir + "/redis.conf";
        platform.writeGenerated(fActions, actions);
        platform.writeGenerated(fGrey, greylistConf);
        platform.writeGenerated(fRedis, redisConf);
        return List.of(fActions, fGrey, fRedis);
    }

    // --- Reloads -----------------------------------------------------------

    private boolean reloadMail() {
        if (!platform.isLinux()) return false;
        boolean ok = platform.exec(20, "postfix", "reload");
        platform.exec(20, "doveadm", "reload");
        platform.exec(20, "systemctl", "reload-or-restart", "opendkim");
        return ok;
    }

    static String localPart(String email) {   // package-private for unit tests
        int at = email.indexOf('@');
        return at > 0 ? email.substring(0, at) : email;
    }
}
