package sh.ravix.platform;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.transaction.Transactional;
import java.util.ArrayList;
import java.util.List;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jboss.logging.Logger;
import sh.ravix.entity.AppSetting;
import sh.ravix.entity.Mailbox;

/**
 * Manages Radicale — a lightweight CalDAV/CardDAV server — so each mailbox
 * gets calendar + contacts using the SAME credentials as their mail login.
 *
 * Radicale authenticates against an htpasswd file in bcrypt mode. Our
 * mailbox password hashes are already bcrypt ($2a$…), so the same hash that
 * Dovecot uses for IMAP works verbatim for CalDAV/CardDAV — one password
 * across mail, calendar and contacts.
 *
 * Storage lives under {@code <vmail>/radicale-collections}; the service runs
 * on 127.0.0.1:5232 and is exposed at {@code /dav/} by the panel's nginx.
 */
@ApplicationScoped
public class RadicaleService {

    private static final Logger LOG = Logger.getLogger(RadicaleService.class);

    private static final String VENV = "/opt/ravix/radicale-venv";
    private static final String BIN = VENV + "/bin/radicale";
    private static final String CONFIG = "/etc/radicale/config";
    private static final String HTPASSWD = "/etc/radicale/users";
    private static final String UNIT = "/etc/systemd/system/radicale.service";

    @ConfigProperty(name = "ravix.provision.vmail-base") String vmailBase;

    @Inject PlatformService platform;

    public boolean isInstalled() {
        return platform.fileExists(BIN);
    }

    public boolean isRunning() {
        return platform.isLinux()
                && "active".equals(platform.run(3, "systemctl", "is-active", "radicale").orElse("").trim());
    }

    // --- Install -----------------------------------------------------------

    /** Install Radicale into a venv (idempotent) and lay down config + unit. */
    public void install(TaskService.LogSink sink) {
        if (!platform.isLinux()) {
            sink.append("Not on Linux — skipping Radicale install.");
            return;
        }
        sink.append("▸ Ensuring python3-venv is present…");
        platform.runEnv(180, java.util.Map.of("DEBIAN_FRONTEND", "noninteractive"),
                "apt-get", "install", "-y", "python3-venv", "python3-pip");

        if (!platform.fileExists(BIN)) {
            sink.append("▸ Creating venv at " + VENV + " and installing Radicale (pip)…");
            platform.exec(60, "python3", "-m", "venv", VENV);
            platform.run(300, VENV + "/bin/pip", "install", "--upgrade", "pip");
            var r = platform.run(300, VENV + "/bin/pip", "install", "radicale", "passlib", "bcrypt");
            r.ifPresent(sink::append);
        } else {
            sink.append("▸ Radicale already installed in venv.");
        }

        // The unit runs as User=vmail — make sure that account exists, or
        // radicale.service fails to start with "user vmail not found". The mail
        // packages don't create it; this mirrors ProvisioningService.ensureMailStorage.
        sink.append("▸ Ensuring the vmail account exists…");
        platform.exec(5, "bash", "-c", "getent group vmail >/dev/null 2>&1 || groupadd vmail");
        platform.exec(5, "bash", "-c",
                "getent passwd vmail >/dev/null 2>&1 || useradd -r -g vmail "
                        + "-d " + vmailBase + " -s /usr/sbin/nologin vmail");

        String collections = vmailBase + "/radicale-collections";
        platform.exec(5, "mkdir", "-p", collections, "/etc/radicale");
        platform.exec(5, "chown", "-R", "vmail:vmail", collections);

        sink.append("▸ Writing config + systemd unit…");
        writeConfig(collections);
        writeUnit();
        // Seed the htpasswd from current mailboxes.
        syncUsers();

        platform.exec(10, "systemctl", "daemon-reload");
        platform.exec(15, "systemctl", "enable", "--now", "radicale");
        sink.append("✓ Radicale installed and started on 127.0.0.1:5232 (exposed at /dav/).");
    }

    public void uninstall(TaskService.LogSink sink) {
        platform.exec(15, "systemctl", "disable", "--now", "radicale");
        platform.exec(5, "rm", "-f", UNIT);
        platform.exec(10, "systemctl", "daemon-reload");
        platform.exec(10, "rm", "-rf", VENV);
        sink.append("✓ Radicale removed. Collections under " + vmailBase + "/radicale-collections kept.");
    }

    // --- Config rendering --------------------------------------------------

    private void writeConfig(String collections) {
        String cfg = """
                # Generated by Ravix — do not edit by hand.
                [server]
                hosts = 127.0.0.1:5232

                [auth]
                type = htpasswd
                htpasswd_filename = %s
                htpasswd_encryption = bcrypt

                [storage]
                filesystem_folder = %s

                [rights]
                type = owner_only

                [web]
                type = internal
                """.formatted(HTPASSWD, collections);
        platform.writeGenerated(CONFIG, cfg);
    }

    private void writeUnit() {
        String unit = """
                [Unit]
                Description=Radicale CalDAV/CardDAV server (Ravix)
                After=network.target

                [Service]
                ExecStart=%s --config %s
                User=vmail
                Group=vmail
                Restart=on-failure

                [Install]
                WantedBy=multi-user.target
                """.formatted(BIN, CONFIG);
        platform.writeGenerated(UNIT, unit);
    }

    /** Rebuild the htpasswd from active mailboxes. Their bcrypt hashes work
     *  directly — same password as IMAP. Called on install and whenever
     *  mailboxes change (ProvisioningService.syncMailData). */
    @Transactional
    public void syncUsers() {
        if (!platform.isLinux() || !platform.fileExists(CONFIG)) return;
        StringBuilder sb = new StringBuilder();
        for (Mailbox m : Mailbox.<Mailbox>list("status", "active")) {
            if (m.passwordHash == null || m.passwordHash.isBlank()) continue;
            // htpasswd line: user:bcrypt-hash. Dovecot stores the bare $2a$… hash.
            sb.append(m.email).append(':').append(m.passwordHash).append('\n');
        }
        platform.writeGenerated(HTPASSWD, sb.toString());
        platform.exec(5, "chown", "vmail:vmail", HTPASSWD);
        platform.exec(5, "chmod", "640", HTPASSWD);
        if (isRunning()) {
            // Radicale reads htpasswd per-request, no reload needed; restart only
            // if the unit somehow isn't picking up — keep it cheap (no-op here).
            LOG.debugf("Radicale htpasswd synced (%d users)", sb.toString().split("\n").length);
        }
    }

    // --- Status for the UI -------------------------------------------------

    public record Status(boolean installed, boolean running, int users, String baseUrl) {}

    public Status status() {
        String host = mailHostname();
        int users = (int) Mailbox.count("status", "active");
        return new Status(isInstalled(), isRunning(), users, "https://" + host + "/dav/");
    }

    private String mailHostname() {
        AppSetting h = AppSetting.findById("hostname");
        return h != null && h.value != null && !h.value.isBlank() ? h.value : platform.hostname();
    }

    /** nginx vhost snippet exposing Radicale at /dav/. Returned to
     *  ProvisioningService so it's written alongside the other panel config. */
    public List<String> renderNginx() {
        List<String> touched = new ArrayList<>();
        if (!platform.isLinux() || !platform.fileExists("/etc/nginx/sites-available")) return touched;
        String confPath = "/etc/nginx/sites-available/ravix-dav.conf";
        String linkPath = "/etc/nginx/sites-enabled/ravix-dav.conf";
        String host = mailHostname();
        String certDir = "/etc/letsencrypt/live/" + host;
        boolean haveCert = platform.fileExists(certDir + "/fullchain.pem");

        StringBuilder c = new StringBuilder();
        c.append("# Generated by Ravix — CalDAV/CardDAV (Radicale) proxy.\n");
        c.append("server {\n");
        if (haveCert) {
            c.append("    listen 443 ssl;\n    listen [::]:443 ssl;\n");
            c.append("    ssl_certificate ").append(certDir).append("/fullchain.pem;\n");
            c.append("    ssl_certificate_key ").append(certDir).append("/privkey.pem;\n");
        } else {
            c.append("    listen 80;\n");
        }
        c.append("    server_name ").append(host).append(";\n\n");
        c.append("    location /dav/ {\n");
        c.append("        proxy_pass http://127.0.0.1:5232/;\n");
        c.append("        proxy_set_header Host $host;\n");
        c.append("        proxy_set_header X-Script-Name /dav;\n");
        c.append("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n");
        c.append("        proxy_pass_header Authorization;\n");
        c.append("    }\n");
        // Well-known service discovery so clients only need the bare domain.
        c.append("    location = /.well-known/caldav { return 301 /dav/; }\n");
        c.append("    location = /.well-known/carddav { return 301 /dav/; }\n");
        c.append("}\n");

        String existing = platform.readFile(confPath).orElse("");
        boolean changed = false;
        if (!existing.equals(c.toString())) {
            platform.writeGenerated(confPath, c.toString());
            changed = true;
        }
        if (!platform.fileExists(linkPath)) {
            platform.exec(5, "ln", "-sf", confPath, linkPath);
            changed = true;
        }
        if (changed && platform.exec(10, "nginx", "-t")) {
            platform.exec(10, "systemctl", "reload", "nginx");
        }
        touched.add(confPath);
        return touched;
    }
}
