package sh.ravix.platform;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.transaction.Transactional;
import java.nio.file.Path;
import java.util.List;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jboss.logging.Logger;
import sh.ravix.entity.Mailbox;
import sh.ravix.entity.MailFilter;

/**
 * Renders a mailbox's {@link MailFilter} rules into a Sieve script that
 * Dovecot/Pigeonhole runs at delivery time (LMTP). Rules thus apply even when
 * webmail is closed, exactly like a real mail provider.
 *
 * Script lives at {@code <vmail>/<domain>/<local>/.dovecot.sieve} which is the
 * per-user default sieve location Ravix configures in Dovecot.
 */
@ApplicationScoped
public class SieveService {

    private static final Logger LOG = Logger.getLogger(SieveService.class);

    @ConfigProperty(name = "ravix.provision.vmail-base") String vmailBase;

    @Inject PlatformService platform;

    /** IMAP/Sieve folder name for fileinto, per canonical folder key. */
    private static String sieveFolder(String key) {
        return switch (key == null ? "" : key) {
            case "spam" -> "Junk";
            case "sent" -> "Sent";
            case "drafts" -> "Drafts";
            case "trash" -> "Trash";
            case "archive" -> "Archive";
            case "inbox", "" -> "INBOX";
            default -> key;   // custom folder
        };
    }

    @Transactional
    public void rebuild(Mailbox m) {
        List<MailFilter> rules = MailFilter.list(
                "mailboxId = ?1 and enabled = true",
                io.quarkus.panache.common.Sort.by("ord"), m.id);
        String script = render(rules);

        int at = m.email.indexOf('@');
        String local = at > 0 ? m.email.substring(0, at) : m.email;
        String domain = at > 0 ? m.email.substring(at + 1) : m.domain;
        Path home = Path.of(vmailBase, domain, local);
        Path sieve = home.resolve(".dovecot.sieve");

        platform.writeGenerated(sieve.toString(), script);
        if (platform.isLinux()) {
            platform.exec(5, "chown", "vmail:vmail", sieve.toString());
            // Compile to .svbin so Pigeonhole doesn't recompile per delivery.
            platform.exec(15, "sievec", sieve.toString());
            platform.exec(5, "chown", "vmail:vmail",
                    home.resolve(".dovecot.svbin").toString());
        }
    }

    String render(List<MailFilter> rules) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by Ravix — do not edit by hand.\n");
        sb.append("require [\"fileinto\", \"imap4flags\"];\n\n");
        for (MailFilter r : rules) {
            String header = switch (r.field == null ? "from" : r.field) {
                case "to" -> "to";
                case "subject" -> "subject";
                default -> "from";
            };
            String matcher = "is".equals(r.op) ? ":is" : ":contains";
            sb.append("# ").append(r.name == null ? r.id : r.name).append("\n");
            sb.append("if header ").append(matcher).append(" \"")
              .append(header).append("\" \"").append(escape(r.value)).append("\" {\n");
            switch (r.action == null ? "fileinto" : r.action) {
                case "discard" -> sb.append("    discard;\n    stop;\n");
                case "mark_read" -> sb.append("    setflag \"\\\\Seen\";\n");
                case "star" -> sb.append("    setflag \"\\\\Flagged\";\n");
                default -> {  // fileinto
                    sb.append("    fileinto \"").append(sieveFolder(r.target)).append("\";\n");
                    sb.append("    stop;\n");
                }
            }
            sb.append("}\n\n");
        }
        return sb.toString();
    }

    private static String escape(String s) {
        return s == null ? "" : s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
