package sh.ravix.platform;

import java.util.List;

/**
 * Catalog of the software components Ravix can manage on the host: which apt
 * package backs each one, its systemd unit (if any) and editable config files.
 * Config paths here also form the write whitelist for the config editor.
 */
public final class SoftwareCatalog {

    private SoftwareCatalog() {}

    public record ConfigFile(String path, String label) {}

    public record Component(
            String id,
            String name,
            String description,
            String pkg,
            String unit,           // systemd unit, or null if not a service
            List<ConfigFile> configs) {}

    public static final List<Component> COMPONENTS = List.of(
            new Component("postfix", "Postfix", "SMTP / mail transfer agent",
                    "postfix", "postfix", List.of(
                    new ConfigFile("/etc/postfix/main.cf", "main.cf"),
                    new ConfigFile("/etc/postfix/master.cf", "master.cf"))),
            new Component("dovecot", "Dovecot", "IMAP / POP3 / LMTP delivery + Sieve",
                    // imapd = IMAP server, pop3d = POP3 server, lmtpd = the LMTP
                    // delivery agent Postfix hands incoming mail to, sieve =
                    // Pigeonhole for server-side filters. pop3d is required
                    // because the rendered config sets `protocols = imap pop3
                    // lmtp` (and the firewall opens 110/995) — without it
                    // Dovecot fails to start: service(pop3) access … No such file.
                    "dovecot-imapd dovecot-pop3d dovecot-lmtpd dovecot-sieve", "dovecot", List.of(
                    new ConfigFile("/etc/dovecot/dovecot.conf", "dovecot.conf"),
                    new ConfigFile("/etc/dovecot/conf.d/10-mail.conf", "10-mail.conf"))),
            new Component("rspamd", "Rspamd", "Spam filtering & scoring",
                    "rspamd", "rspamd", List.of(
                    new ConfigFile("/etc/rspamd/rspamd.conf", "rspamd.conf"),
                    new ConfigFile("/etc/rspamd/local.d/options.inc", "options.inc"))),
            new Component("nginx", "Nginx", "Reverse proxy / webmail",
                    "nginx", "nginx", List.of(
                    new ConfigFile("/etc/nginx/nginx.conf", "nginx.conf"))),
            new Component("redis", "Redis", "Cache backend for Rspamd",
                    "redis-server", "redis-server", List.of(
                    new ConfigFile("/etc/redis/redis.conf", "redis.conf"))),
            new Component("opendkim", "OpenDKIM", "DKIM signing milter",
                    "opendkim", "opendkim", List.of(
                    new ConfigFile("/etc/opendkim.conf", "opendkim.conf"))),
            new Component("certbot", "Certbot", "Let's Encrypt ACME client",
                    "certbot", null, List.of(
                    new ConfigFile("/etc/letsencrypt/cli.ini", "cli.ini"))),
            // PostgreSQL and fail2ban are installed by install.sh, but listing
            // them here makes /software show their status alongside the mail
            // stack — operator gets one place to see "is the whole host healthy".
            new Component("postgresql", "PostgreSQL", "Panel database",
                    "postgresql", "postgresql", List.of(
                    new ConfigFile("/etc/postgresql/15/main/postgresql.conf", "postgresql.conf"),
                    new ConfigFile("/etc/postgresql/15/main/pg_hba.conf", "pg_hba.conf"))),
            new Component("fail2ban", "fail2ban", "Brute-force protection (SSH / SMTP / IMAP)",
                    "fail2ban", "fail2ban", List.of(
                    new ConfigFile("/etc/fail2ban/jail.local", "jail.local"),
                    new ConfigFile("/etc/fail2ban/jail.d/ravix.local", "ravix.local"))),
            // Radicale — CalDAV/CardDAV server (calendar + contacts). Installed
            // from pip into a venv by Ravix (the Debian package is old); the
            // systemd unit + config are generated by ProvisioningService.
            new Component("radicale", "Radicale", "Calendar & contacts (CalDAV/CardDAV)",
                    "python3-venv", "radicale", List.of(
                    new ConfigFile("/etc/radicale/config", "config"))));

    public static Component byId(String id) {
        return COMPONENTS.stream().filter(c -> c.id().equals(id)).findFirst().orElse(null);
    }

    /** All config paths across the catalog — the write whitelist. */
    public static boolean isAllowedConfigPath(String path) {
        return COMPONENTS.stream()
                .flatMap(c -> c.configs().stream())
                .anyMatch(f -> f.path().equals(path));
    }
}
